// <auto-generated />
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReactAppNetCore.Server.Repositories;

#nullable disable

namespace ReactAppNetCore.Server.Migrations
{
    [DbContext(typeof(FormDBContext))]
    partial class FormDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReactAppNetCore.Server.Models.Control", b =>
                {
                    b.Property<int>("templateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<int>("fieldNo")
                        .HasColumnType("integer")
                        .HasColumnName("field_no");

                    b.Property<JsonDocument>("taskData")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("task_data");

                    b.HasKey("templateId", "fieldNo");

                    b.ToTable("control");
                });

            modelBuilder.Entity("ReactAppNetCore.Server.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("template");
                });

            modelBuilder.Entity("ReactAppNetCore.Server.Models.Control", b =>
                {
                    b.HasOne("ReactAppNetCore.Server.Models.Template", "template")
                        .WithMany("controls")
                        .HasForeignKey("templateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("template");
                });

            modelBuilder.Entity("ReactAppNetCore.Server.Models.Template", b =>
                {
                    b.Navigation("controls");
                });
#pragma warning restore 612, 618
        }
    }
}
